routes/admin_route.py
from flask import Blueprint, redirect, request, jsonify, session, render_template
from guard import login_required
from services.stats_service import (
    bussiness_stats as bussiness,
    products_stats as products,
    tags_stats as tags,
    users_stats as users,
)
from helpers import set_pagination, status_list, type_list, roles_list
from services.products_service import get_by_status as products_by_status
from services.bussiness_service import get_by_status as bussinnes_by_status
from services.tags_service import get_by_status as tags_by_status
from services.users_service import (
    get as get_user,
    update_role,
    update as update_user,
)
from flask_login import current_user

# TODO: Protect
admin_bp = Blueprint("admin", __name__)


@admin_bp.route("/", methods=["GET"])
def stats():
    bussiness_stats = bussiness()
    users_stats = users()
    products_stats = products()
    tags_stats = tags()
    return render_template(
        "dashboards/admin_dashboard.html",
        bussiness=bussiness_stats,
        users=users_stats,
        products=products_stats,
        tags=tags_stats,
    )


@admin_bp.route("/search", methods=["GET"])
def general_search():

    type = request.args.get("type", "products")
    [start_pagination, end_pagination] = set_pagination(None)
    if type == "products":
        [response, count] = products_by_status(
            "approved", start_pagination, end_pagination, ""
        )
    elif type == "bussiness":
        [response, count] = bussinnes_by_status(
            "approved", start_pagination, end_pagination, ""
        )
    elif type == "tags":
        [response, count] = tags_by_status(
            "approved", start_pagination, end_pagination, ""
        )
    else:
        [response, count] = products_by_status(  # users by status
            "approved", start_pagination, end_pagination, ""
        )

    return render_template(
        "search/admin_search.html",
        items=response,
        pages=count / 12,  # 12 per page
    )


@admin_bp.route("/profile-edit", methods=["GET"])
def edit_profile_from_admin():
    id = request.args.get("id")
    response = get_user(id)
    return render_template("admin/edit_user.html", user=response)


@admin_bp.route("/edit-user", methods=["PUT"])
def update_profile_from_admin():
    data = request.get_json()
    id = request.args.get("id")
    if data.get("role") not in roles_list:
        return "Role not found", 400
    update_user(id, data)
    update_role(id, data.get("role"))
    return "Success!"


@admin_bp.before_request
@login_required()
def before_request():
    if not current_user.has_role("ADMIN"):
        return redirect("/unauthorized")

routes/owner_route.py
from flask import Blueprint, request, render_template, redirect, jsonify
from guard import *
from flask_login import current_user
from helpers import roles_list, set_pagination, filter_list
from services.products_service import (
    get_popular_by_owner as products_popular,
    get_top_rated_by_owner as products_top_rated,
)
from services.brands_service import *
from services.bussiness_service import (
    get_by_owner_popular as bussiness_popular,
    get_by_owner as bussiness_all,
    get_by_owner_top_rated as bussiness_top_rated,
)
from services.stocks_service import get_by_bussiness as stock_bussiness

owner_bp = Blueprint("owner", __name__)


@owner_bp.route("/dashboard", methods=["GET"])
def main():
    owner = current_user.get_id() or 3
    [popular_products, count] = products_popular(owner, limited=True)
    [popular_bussiness, count] = bussiness_popular(owner, limited=True)
    [unpopular_bussiness, count] = bussiness_popular(owner, limited=True, order="ASC")
    [unpopular_products, count] = products_popular(owner, limited=True, order="ASC")
    [top_rated_bussiness, count] = bussiness_top_rated(owner, limited=True)
    [top_rated_products, count] = products_top_rated(owner, limited=True)
    [less_rated_bussiness, count] = bussiness_top_rated(
        owner, limited=True, order="ASC"
    )
    [less_rated_products, count] = products_top_rated(owner, limited=True, order="ASC")
    # print("wut")
    # print(popular_products)
    return render_template(
        "/dashboards/owner_dashboard.html",
        popular_products=popular_products,
        popular_bussiness=popular_bussiness,
        less_rated_products=less_rated_products,
        top_rated_products=top_rated_products,
        unpopular_bussiness=unpopular_bussiness,
        unpopular_products=unpopular_products,
        top_rated_bussiness=top_rated_bussiness,
        less_rated_bussiness=less_rated_bussiness,
    )
    # return render_template('',
    #                        popular_products=popular_products, popular_bussiness=popular_bussiness,
    #                        unpopular_bussiness=unpopular_bussiness)


@owner_bp.route("/search", methods=["GET"])
def general_search():
    owner_id = current_user.get_id()
    type = request.args.get("type", "products")
    filter = request.args.get("filter", "popular")
    [start_pagination, end_pagination] = set_pagination(None)
    if type == "products":
        if filter == "popular":
            print("OWNER ID", owner_id)
            [response, count] = products_popular(
                owner_id, False, start_pagination, end_pagination
            )
        elif filter == "top_rated":
            [response, count] = products_top_rated(
                owner_id, False, start_pagination, end_pagination
            )
        elif filter == "less_rated":
            [response, count] = products_top_rated(
                owner_id, False, start_pagination, end_pagination, order="ASC"
            )
        elif filter == "unpopular":
            [response, count] = products_popular(
                owner_id, False, start_pagination, end_pagination, order="ASC"
            )
    elif type == "bussiness":
        if filter == "popular":
            [response, count] = bussiness_popular(
                owner_id, False, start_pagination, end_pagination
            )
        elif filter == "top_rated":
            [response, count] = bussiness_top_rated(
                owner_id, False, start_pagination, end_pagination
            )
        elif filter == "less_rated":
            [response, count] = bussiness_top_rated(
                owner_id, False, start_pagination, end_pagination, order="ASC"
            )
        elif filter == "unpopular":
            [response, count] = bussiness_popular(
                owner_id, False, start_pagination, end_pagination, order="ASC"
            )

    return render_template(
        "search/owner_search.html",
        items=response,
        pages=count / 12,  # 12 per page
    )


@owner_bp.route("/bussiness/popular", methods=["GET"])
def popular_bussiness():
    page = request.args.get("page", None)
    name = request.args.get("name", "")
    status = request.args.get("status", None)
    if status not in status_list:
        return "error"
    owner = current_user.get_id()
    [start_pagination, end_pagination] = set_pagination(page)
    [response, count] = bussiness_popular(
        owner,
        start_page=start_pagination,
        end_page=end_pagination,
        order="ASC",
        word=name,
        status=status,
    )
    return jsonify({"data": response, "count": count / 12})
    # return render_template('', bussiness=response)


@owner_bp.route("/bussiness/unpopular", methods=["GET"])
def unpopular_bussiness():
    page = request.args.get("page", None)
    name = request.args.get("name", "")
    status = request.args.get("status", None)
    if status not in status_list:
        return "error"
    owner = current_user.get_id()
    [start_pagination, end_pagination] = set_pagination(page)
    [response, count] = bussiness_popular(
        owner,
        start_page=start_pagination,
        end_page=end_pagination,
        word=name,
        status=status,
    )
    return jsonify({"data": response, "count": count / 12})

    # return render_template('', bussiness=response)


@owner_bp.route("/products/popular", methods=["GET"])
def popular_products():
    page = request.args.get("page", None)
    name = request.args.get("name", "")
    status = request.args.get("status", None)
    if status not in status_list:
        return "error"
    owner = current_user.get_id()
    [start_pagination, end_pagination] = set_pagination(page)
    [response, count] = products_popular(
        owner,
        start_page=start_pagination,
        end_page=end_pagination,
        word=name,
        status=status,
    )
    return jsonify({"data": response, "count": count / 12})

    # return render_template('', products=response)


@owner_bp.route("/bussiness/less_rated", methods=["GET"])
def less_rated_bussiness():
    page = request.args.get("page", None)
    name = request.args.get("name", "")
    status = request.args.get("status", None)
    if status not in status_list:
        return "error"
    owner = current_user.get_id()
    [start_pagination, end_pagination] = set_pagination(page)
    [response, count] = bussiness_top_rated(
        owner,
        start_page=start_pagination,
        end_page=end_pagination,
        order="ASC",
        word=name,
        status=status,
    )
    return jsonify({"data": response, "count": count / 12})

    # return render_template('', products=response)


@owner_bp.route("/bussiness/top_rated", methods=["GET"])
def top_rated_bussiness():
    page = request.args.get("page", None)
    name = request.args.get("name", "")
    status = request.args.get("status", None)
    if status not in status_list:
        return "error"
    owner = current_user.get_id()
    [start_pagination, end_pagination] = set_pagination(page)
    [response, count] = bussiness_top_rated(
        owner,
        start_page=start_pagination,
        end_page=end_pagination,
        word=name,
        status=status,
    )
    return jsonify({"data": response, "count": count / 12})

    # return render_template('', products=response)


@owner_bp.route("/products/top_rated", methods=["GET"])
def top_rated_products():
    page = request.args.get("page", None)
    name = request.args.get("name", "")
    status = request.args.get("status", None)
    if status not in status_list:
        return "error"
    owner = current_user.get_id()
    [start_pagination, end_pagination] = set_pagination(page)
    [response, count] = products_top_rated(
        owner,
        start_page=start_pagination,
        end_page=end_pagination,
        word=name,
        status=status,
    )
    return jsonify({"data": response, "count": count / 12})

    # return render_template('', products=response)


@owner_bp.route("/products/less_rated", methods=["GET"])
def less_rated_products():
    page = request.args.get("page", None)
    name = request.args.get("name", "")
    status = request.args.get("status", None)
    if status not in status_list:
        return "error"
    owner = current_user.get_id()
    [start_pagination, end_pagination] = set_pagination(page)
    [response, count] = products_top_rated(
        owner,
        start_page=start_pagination,
        end_page=end_pagination,
        order="ASC",
        word=name,
        status=status,
    )
    return jsonify({"data": response, "count": count / 12})

    # return render_template('', products=response)


@owner_bp.route("/products/unpopular", methods=["GET"])
def unpopular_products():
    page = request.args.get("page", None)
    name = request.args.get("name", "")
    status = request.args.get("status", None)
    if status not in status_list:
        return "error"
    owner = current_user.get_id()
    [start_pagination, end_pagination] = set_pagination(page)
    [response, count] = products_popular(
        owner,
        start_page=start_pagination,
        end_page=end_pagination,
        order="ASC",
        word=name,
        status=status,
    )
    return jsonify({"data": response, "count": count / 12})

    # return render_template('', products=response)


@owner_bp.route("/<slug>/stocks", methods=["GET"])
def stocks(slug):
    owner = current_user.get_id()
    page = request.args.get("page", None)
    name = request.args.get("name", "")
    status = request.args.get("status", None)
    if status not in status_list:
        return "error"
    [start_pagination, end_pagination] = set_pagination(page)
    [response, count] = stock_bussiness(slug, owner, start_pagination, end_pagination)
    return jsonify({"data": response, "count": count / 12})

    # return render_template('', stocks=response)


@owner_bp.before_request
@login_required()
def before_request():
    if not current_user.has_role("OWNER"):

routes/stocks_route.py
from flask import Blueprint, request, render_template, jsonify
from services.stocks_service import *
from flask_login import current_user
from services.products_service import get_all as get_all_products
from services.bussiness_service import get_by_owner as get_bussiness_by_owner
from helpers import set_pagination
from guard import belongs_to_owner, role_required, secure_access

stocks_bp = Blueprint("stocks", __name__)


@stocks_bp.route("/test", methods=["GET"])
def index():
    return "Hello Stocks!"


@stocks_bp.route("/all", methods=["GET"])
def find_all():
    response = get_all()
    return jsonify(response)


@stocks_bp.route("/", methods=["GET"])
def find():
    id = request.args.get("id")
    response = get(id)
    return jsonify(response)


@stocks_bp.route("/", methods=["POST"])
def create():
    data = request.get_json()
    response = insert(data)
    return jsonify(response)


@stocks_bp.route("/", methods=["PUT"])
@belongs_to_owner()
def edit():
    data = request.get_json()
    id = request.args.get("id")
    response = update(id, data)
    return jsonify(response)


@stocks_bp.route("/", methods=["DELETE"])
def remove():
    id = request.args.get("id")
    response = delete(id)
    return "Success!"


@stocks_bp.route("/form", methods=["GET"])
@role_required("OWNER")
def form():
    id = request.args.get("id", None)
    if id:
        stock = get(id)
    else:
        stock = [None]
    owner_id = current_user.get_id() or 3
    products = get_all_products()
    bussiness = get_bussiness_by_owner(owner_id, None, None)
    return render_template(
        "form_create/form_create_stock.html",
        products=products,
        bussiness=bussiness,
        stock=stock,
    )


@stocks_bp.route("/edit/form", methods=["GET"])
def edit_form():
    return render_template("")


#################################


@stocks_bp.route("/bussiness", methods=["GET"])
@secure_access()
def find_by_bussiness():
    owner_id = request.args.get("owner_id")
    bussiness_id = request.args.get("bussiness_id")
    page = request.args.get("page", None)
    [start_pagination, end_pagination] = set_pagination(page)
    response = get_by_bussiness(
        bussiness_id, owner_id, start_pagination, end_pagination
    )
    return jsonify(response)

routes/users_route.py
from helpers import roles_list, set_pagination
from guard import role_required
from flask import Blueprint, request, jsonify, render_template
from flask_login import current_user
from services.auth_service import verify_existing_email
from services.lists_services import get_by_user as list_user
from services.ratings_service import get_by_user as ratings_user
from services.users_service import *
from guard import login_required, secure_access

users_bp = Blueprint("users", __name__)


# BASIC #DONE


@users_bp.route("/test", methods=["GET"])
def index():
    return "Hello Users!"


@users_bp.route("/", methods=["GET"])
@role_required(roles_list["admin"])
def find():
    id = request.args.get("id")
    response = get(id)
    return jsonify(response)


@users_bp.route("/all", methods=["GET"])
def find_all():
    page = request.args.get("page", None)
    to_json = request.args.get("json", False)
    name = request.args.get("name", "")
    type = request.args.get("type", None)
    [start_pagination, end_pagination] = set_pagination(page)
    [response, count] = get_all(name, type, start_pagination, end_pagination)
    if to_json:
        return jsonify({"data": response, "count": count, "pages": count / 12})
    return render_template(
        "/admin/users_manager.html",
        users=response,
        count=count,
        pages=count / 12,
    )


@users_bp.route("/", methods=["POST"])
def create():
    data = request.get_json()
    response = insert(data)
    return jsonify(response)


@users_bp.route("/", methods=["PUT"])
def edit():
    id = current_user.get_id() or 3
    data = request.get_json()
    if verify_existing_email(data.get("email")):
        return "Email already exists", 400
    response = update(id, data)
    return "Success!"


@users_bp.route("/", methods=["DELETE"])
def remove():
    id = request.args.get("id")
    response = delete(id)
    print(response)
    return "Success!"


# CLIENT


# @users_bp.route("/become-owner", methods=["GET"])
# @login_required()
# def become_owner():
# TODO: check if user is already an owner
# TODO: logic for create bussiness
# return render_template("create_owner")


@users_bp.route("/profile-edit", methods=["GET"])
@login_required()
def edit_profile():
    id = current_user.get_id() or 3
    response = get(id)
    return render_template("auth/form_edit_user.html", user=response)


@users_bp.route("/admin/update-role", methods=["GET"])
@login_required()
def edit_role():
    id = request.args.get("id")
    response = get(id)
    return render_template("auth/form_edit_user.html", user=response)


@users_bp.route("/my-list", methods=["GET"])
@secure_access()
def get_list():
    response = list_user(request.args.get("user_id"))
    return jsonify(response)


@users_bp.route("/my-ratings", methods=["GET"])
def get_ratings():
    response = ratings_user(current_user.get_id())
    return render_template("", ratings=response)

templates/dashboards/admin_dashboard.html
{% extends 'base.html' %}

{% block content %}
<div class="container tw-flex tw-flex-col tw-gap-12">
    <!-- users count -->
    <div class="container-title tw-flex tw-gap-6">
        <div>
            <h1 class="tw-font-semibold tw-text-4xl tw-mt-2 tw-mb-4">Welcome {{ current_user.name }}</h1>
        </div>
        <a class="btn btn-primary tw-h-fit tw-self-center" href="{{url_for('brands.form')}}">Create
            Brand</a>
        <a class="btn btn-primary tw-h-fit tw-self-center" href="{{url_for('products.form')}}">Create Products</a>
        <a class="btn btn-primary tw-h-fit tw-self-center" href="{{url_for('admin.general_search')}}">Go Search</a>

    </div>
    <div class="tw-text-center">
        <div class="container-title tw-flex tw-gap-6 tw-mb-4">
            <h2 class="tw-font-semibold tw-text-3xl tw-mb-4 tw-inline-block">Users Count</h2>
            <div class="tw-inline-block tw-h-[3px] tw-grow tw-shrink tw-self-center tw-bg-baseblue">
            </div>
            <a class="btn btn-outline-primary tw-h-fit tw-self-center" href="{{url_for('users.find_all')}}">Manage</a>
        </div>
        <div class="container tw-flex tw-w-full tw-gap-3">
            <div class="card tw-w-full tw-pb-4 tw-pt-2">
                <div class="card-title tw-text-lg">Total Users</div>
                <div class="card-body tw-text-4xl tw-font-semibold">
                    {{ users.count }}
                </div>
            </div>
            <div class="card tw-w-full tw-pb-4 tw-pt-2">
                <div class="card-title tw-text-lg">Total Owners</div>
                <div class="card-body tw-text-4xl tw-font-semibold">
                    {{ users.owner_count }}
                </div>
            </div>
            <div class="card tw-w-full tw-pb-4 tw-pt-2">
                <div class="card-title tw-text-lg">Total Clients</div>
                <div class="card-body tw-text-4xl tw-font-semibold">
                    {{ users.user_count }}
                </div>
            </div>

        </div>
    </div>
    <!-- bussiness count -->

    <div class="tw-text-center">
        <div class="container-title tw-flex tw-gap-6 tw-mb-4">
            <h2 class="tw-font-semibold tw-text-3xl tw-mb-4 tw-inline-block">Bussiness Count</h2>
            <div class="tw-inline-block tw-h-[3px] tw-grow tw-shrink tw-self-center tw-bg-baseblue">
            </div>
            <a class="btn btn-outline-primary tw-h-fit tw-self-center"
                href="{{url_for('admin.general_search', type='bussiness')}}">Manage</a>
        </div>
        <div class="container tw-flex tw-w-full tw-gap-3">
            <div class="card tw-w-full tw-pb-4 tw-pt-2">
                <div class="card-title tw-text-lg">Total Bussiness</div>
                <div class="card-body tw-text-4xl tw-font-semibold">
                    {{ bussiness.count }}
                </div>
            </div>
            <div class="card tw-w-full tw-pb-4 tw-pt-2">
                <div class="card-title tw-text-lg">Approved</div>
                <div class="card-body tw-text-4xl tw-font-semibold">
                    {{ bussiness.approved }}
                </div>
            </div>
            <div class="card tw-w-full tw-pb-4 tw-pt-2">
                <div class="card-title tw-text-lg">Rejected</div>
                <div class="card-body tw-text-4xl tw-font-semibold">
                    {{ bussiness.rejected }}
                </div>
            </div>
            <div class="card tw-w-full tw-pb-4 tw-pt-2">
                <div class="card-title tw-text-lg">In Review</div>
                <div class="card-body tw-text-4xl tw-font-semibold">
                    {{ bussiness.review }}
                </div>
            </div>

        </div>
    </div>

    <!-- products count -->

    <div class="tw-text-center">
        <div class="container-title tw-flex tw-gap-6 tw-mb-4">
            <h2 class="tw-font-semibold tw-text-3xl tw-mb-4 tw-inline-block">Products Count</h2>
            <div class="tw-inline-block tw-h-[3px] tw-grow tw-shrink tw-self-center tw-bg-baseblue">
            </div>
            <a class="btn btn-outline-primary tw-h-fit tw-self-center"
                href="{{url_for('admin.general_search', type='products')}}">Manage</a>
        </div>
        <div class="container tw-flex tw-w-full tw-gap-3">
            <div class="card tw-w-full tw-pb-4 tw-pt-2">
                <div class="card-title tw-text-lg">Total Products</div>
                <div class="card-body tw-text-4xl tw-font-semibold">
                    {{ products.count }}
                </div>
            </div>
            <div class="card tw-w-full tw-pb-4 tw-pt-2">
                <div class="card-title tw-text-lg">Approved</div>
                <div class="card-body tw-text-4xl tw-font-semibold">
                    {{ products.approved }}
                </div>
            </div>
            <div class="card tw-w-full tw-pb-4 tw-pt-2">
                <div class="card-title tw-text-lg">Rejected</div>
                <div class="card-body tw-text-4xl tw-font-semibold">
                    {{ products.rejected }}
                </div>
            </div>
            <div class="card tw-w-full tw-pb-4 tw-pt-2">
                <div class="card-title tw-text-lg">In Review</div>
                <div class="card-body tw-text-4xl tw-font-semibold">
                    {{ products.review }}
                </div>
            </div>

        </div>
    </div>

    <!-- tags count -->

    <div class="tw-text-center">
        <div class="container-title tw-flex tw-gap-6 tw-mb-4">
            <h2 class="tw-font-semibold tw-text-3xl tw-mb-4 tw-inline-block">Tags Count</h2>
            <div class="tw-inline-block tw-h-[3px] tw-grow tw-shrink tw-self-center tw-bg-baseblue">
            </div>
            <a class="btn btn-outline-primary tw-h-fit tw-self-center"
                href="{{url_for('admin.general_search', type='tags')}}">Manage</a>
        </div>
        <div class="container tw-flex tw-w-full tw-gap-3">
            <div class="card tw-w-full tw-pb-4 tw-pt-2">
                <div class="card-title tw-text-lg">Total Tags</div>
                <div class="card-body tw-text-4xl tw-font-semibold">
                    {{ tags.count }}
                </div>
            </div>
            <div class="card tw-w-full tw-pb-4 tw-pt-2">
                <div class="card-title tw-text-lg">Approved</div>
                <div class="card-body tw-text-4xl tw-font-semibold">
                    {{ tags.approved }}
                </div>
            </div>
            <div class="card tw-w-full tw-pb-4 tw-pt-2">
                <div class="card-title tw-text-lg">Rejected</div>
                <div class="card-body tw-text-4xl tw-font-semibold">
                    {{ tags.rejected }}
                </div>
            </div>
            <div class="card tw-w-full tw-pb-4 tw-pt-2">
                <div class="card-title tw-text-lg">In Review</div>
                <div class="card-body tw-text-4xl tw-font-semibold">
                    {{ tags.review }}
                </div>
            </div>

        </div>
    </div>
</div>

{% endblock %}