routes/brands_route.py
from flask import Blueprint, redirect, request, jsonify, render_template, session
from guard import role_required
from services.brands_service import *
from helpers import (
    filter_list,
    roles_list,
    slug_generator,
    type_list,
    set_pagination,
    generate_filename,
)
from services.products_service import (
    get_popular_by_brand as products_popular,
    get_newest_by_brand as produscts_newest,
    get_top_rated_by_brand as products_top_rated,
)
from services.bussiness_service import get_popular_by_brand as bussiness_popular
import bcrypt
from services.images_service import insert as insert_image, update as update_image

brands_bp = Blueprint("brands", __name__)

# BASIC DONE


@brands_bp.route("/test")
def index():
    return "Hello Brands!"


@brands_bp.route("/", methods=["GET"])
def find():
    id = request.args.get("id")
    response = get(id)
    return jsonify(response)


@brands_bp.route("/all", methods=["GET"])
def find_all():
    response = get_all()
    return jsonify(response)


@brands_bp.route("/", methods=["POST"])
@role_required("ADMIN")
def create():
    data = request.form
    image = request.files.get("image")
    image_name = generate_filename(image.filename)
    path = f"static/images/brands/{image_name}"
    response = insert(
        {
            "name": data.get("name"),
            "country": data.get("country"),
            "slug": slug_generator(data.get("name")),
        }
    )
    image.save(path)
    insert_image(image_name, response[0]["id"], "/" + path, "images_brands", "brand_id")
    return jsonify(response)


@brands_bp.route("/", methods=["PUT"])
@role_required("ADMIN")
def edit():
    data = request.form
    id = request.args.get("id")
    response = update(
        id,
        {
            "name": data.get("name"),
            "country": data.get("country"),
            "slug": slug_generator(data.get("name")),
        },
    )
    image = request.files.get("image")
    if image:
        image_name = generate_filename(image.filename)
        path = f"static/images/brands/{image_name}"
        image.save(path)
        update_image(
            image_name,
            response[0]["id"],
            "/" + path,
            "images_brands",
            "brand_id",
        )
    return jsonify(response)


@brands_bp.route("/", methods=["DELETE"])
def remove():
    id = request.args.get("id")
    response = delete(id)
    return "Success!"


@brands_bp.route("/", methods=["PATCH"])
def edit_status():
    status = request.get_json()["status"]
    id = request.args.get("id")
    response = update_status(id, status)
    return "Success!"


@brands_bp.route("/form", methods=["GET"])
def form():
    id = request.args.get("id", None)
    if id:
        brand = get(id)
    else:
        brand = [None]
    return render_template("form_create/form_create_brand.html", brand=brand)


@brands_bp.route("/edit/form", methods=["GET"])
def edit_form():
    return render_template("")


#################################################


@brands_bp.route("/<slug>/bussiness/")
def popular_bussines(slug):
    city = session.get("city")
    page = request.args.get("page", None)
    [start_pagination, end_pagination] = set_pagination(page)
    response = bussiness_popular(city, slug, start_pagination, end_pagination)
    return response


@brands_bp.route("/<slug>/search/products", methods=["GET"])
def find_by_product_filter(slug):
    page = request.args.get("page", None)
    filter = request.args.get("filter", "popular")
    json = request.args.get("json", False)
    name = request.args.get("name", "")
    if filter not in filter_list:
        return "error"
    brand = get_with_details(slug)
    [start_pagination, end_pagination] = set_pagination(page)
    if filter == "top_rated":
        [response, count] = products_top_rated(
            slug, False, start_pagination, end_pagination, word=name
        )
    elif filter == "popular":
        [response, count] = products_popular(
            slug, False, start_pagination, end_pagination, word=name
        )
    else:
        [response, count] = produscts_newest(
            slug, False, start_pagination, end_pagination, word=name
        )
    if json:
        return jsonify({"data": response, "count": count / 12})
    return render_template(
        "search/brand_search.html",
        items=response,
        brand=brand,
        count=count,
        pages=count / 12,
    )


@brands_bp.route("/search/<slug>", methods=["GET"])
def find_by_slug(slug):
    city = session.get("city")
    response = get_with_details(slug)
    [popular, count] = products_popular(slug, True)
    [top_rated, count] = products_top_rated(slug, True)
    [newest, count] = produscts_newest(slug, True)
    [bussiness, count] = bussiness_popular(city, slug, True)
    print("aaaa", response)
    return render_template(
        "details/detail_brand.html",
        brand=response,
        popular=popular,
        top_rated=top_rated,
        newest=newest,
        bussiness=bussiness,
    )


@brands_bp.route("/<status>", methods=["GET"])
def get_brands_by_status(status):
    if status not in status_list:
        return "error"
    name = request.args.get("name", "")
    page = request.args.get("page", None)
    [start_pagination, end_pagination] = set_pagination(page)
    [response, count] = get_by_status(status, start_pagination, end_pagination, name)
    print(response)
    return jsonify({"data": response, "count": count / 12})

routes/ratings_route.py
from flask import Blueprint, render_template, request, jsonify, session
from flask_login import current_user
from services.ratings_service import *
from services.bussiness_service import get_by_slug as get_bussiness
from services.products_service import get_by_slug as get_product
from helpers import set_pagination
from guard import secure_access

ratings_bp = Blueprint("ratings", __name__)


@ratings_bp.route("/", methods=["GET"])
def find():
    id = request.args.get("id")
    response = get(id)
    return jsonify(response)


@ratings_bp.route("/all", methods=["GET"])
def find_all():
    response = get_all()
    return jsonify(response)


@ratings_bp.route("/", methods=["POST"])
# @secure_access()
def create():
    data = request.get_json()
    score = data.get("score", None)
    comment = data.get("comment", None)
    product_id = data.get("product_id", None)
    bussiness_id = data.get("bussiness_id", None)
    user_id = current_user.get_id()
    if not user_id:
        return jsonify({"error": "User not found"}), 404
    response = insert_rating(user_id, bussiness_id, product_id, score, comment)
    return jsonify(response)


# @ratings_bp.route('/', methods=['PUT'])
# @secure_access()
# def edit():
#     id = request.args.get('id')
#     data = request.get_json()
#     response = update(id, data)
#     return jsonify(response)


@ratings_bp.route("/", methods=["DELETE"])
@secure_access()
def remove():
    id = request.args.get("id")
    response = delete(id)
    return jsonify(response)


@ratings_bp.route("/user", methods=["GET"])
@secure_access()
def find_by_user():
    user_id = current_user.get_id()
    response = get_by_user(user_id)
    return jsonify(response)


@ratings_bp.route("/bussiness/<slug>", methods=["GET"])
def find_by_bussiness(slug):
    page = request.args.get("page", None)
    lat = session.get("lat")
    lon = session.get("lon")
    [start_pagination, end_pagination] = set_pagination(page)
    bussiness = get_bussiness(slug, lat, lon)
    [response, count] = get_by_bussiness(
        int(bussiness["id"]), False, start_pagination, end_pagination
    )
    print(bussiness)
    return render_template(
        "ratings/ratings_bussiness.html",
        ratings=response,
        bussiness=bussiness,
        count=count,
        pages=count / 12,
    )


@ratings_bp.route("/product/<slug>", methods=["GET"])
def find_by_product(slug):
    page = request.args.get("page", None)
    [start_pagination, end_pagination] = set_pagination(page)
    product = get_product(slug)
    [response, count] = get_by_product(
        int(product["id"]), False, start_pagination, end_pagination
    )
    return render_template(
        "ratings/ratings_products.html",
        ratings=response,
        product=product,
        count=count,
        pages=count / 12,
    )


@ratings_bp.route("/<type>/<id>/aux", methods=["GET"])
def find_auxiliar(type, id):
    score = request.args.get("score")
    time = request.args.get("time")
    if score not in ["ASC", "DESC"]:
        ValueError("Undefined type")
    if time not in ["ASC", "DESC"]:
        ValueError("Undefined Filter")
    page = request.args.get("page")
    [start_pagination, end_pagination] = set_pagination(page)

    if type == "bussiness":
        [response, count] = get_by_bussiness(
            id, False, start_pagination, end_pagination, score, time
        )
    elif type == "products":
        [response, count] = get_by_product(
            id, False, start_pagination, end_pagination, score, time
        )
    else:
        ValueError("Type not valid")
    return jsonify({"data": response, "count": count / 12})  # 12 per page


# DESUSO


@ratings_bp.route("/bussiness/average", methods=["GET"])
def find_avg_by_bussiness():
    id = request.args.get("id")
    response = get_average_by_bussiness(id)
    return jsonify(response)


@ratings_bp.route("/product/average", methods=["GET"])
def find_avg_by_product():
    id = request.args.get("id")
    response = get_average_by_product(id)
    return jsonify(response)


@ratings_bp.route("/test", methods=["GET"])
def index():
    return "Hello Ratings!"

templates/search/brand_search.html
{% extends 'base.html' %}


{% block content %}

<div class="card tw-flex-tw-gap-3-tw-p-4 tw-w-full tw-h-1/3">
    <!-- --     Image -- -->
    <div class="card-body tw-w-full tw-h-1/3 tw-flex tw-items-center tw-justify-center">
        <img src="{{ brand.path or '/static/images/generic.png' }}" alt="{{ brand.name }}"
            class="card-img tw-w-1/4 tw-h-1/4">
        <!-- --     Description -- -->
        <div class="tw-w-2/3 tw-text-center">
            <h1 class="tw-text-2xl tw-font-bold">{{ brand.name }}</h1>
            <p class="tw-text-sm">{{ brand.country }}</p>

        </div>
    </div>
</div>

<form id="search__for" class="tw-flex tw-flex-col tw-w-full"
    onsubmit="event.preventDefault(); return getResults(this);">
    <div class="container tw-my-4 tw-flex tw-flex-col tw-w-full">
        <!-- Search bar -->
        <p class="tw-text-xl tw-mb-2">
            Enter something you're looking for </p>
        <div id="search__input" class="input-group mb-3">

            <button class="btn btn-primary" id="submit__search__button" type="submit">Search</button>

            <input type="text" name="name" value="{{keyword}}" class="form-control">
            <input type="number" name="page" id="input_page" hidden="true">
        </div>


    </div>
    <div class="tw-flex">
        <!-- Sidebar -->
        <div id="search__sidebar"
            class="bg-primary-subtle text-color-baseblue p-3 tw-w-1/5 tw-rounded-[10px] tw-min-w-min">
            <p class="tw-text-center tw-text-xl tw-font-semibold tw-m-3">Filters</p>
            <select class="form-select flex-grow" aria-label=".form-select-lg example" name="filter"
                id="filter__options">
                <option class="filter-option" value="" selected="selected">-- None --</option>
                <option class="filter-option" value="newest">Newest</option>
                <option class="filter-option" value="popular">Popular</option>
                <option class="filter-option" value="top_rated">Top Rated</option>


            </select>
        </div>
        <!-- Content -->
        <div id="search__container" class="tw-w-4/5 px-2">
            <!-- Elements -->

            <div class="tw-grid tw-grid-cols-[repeat(auto-fill,_minmax(200px,_1fr))] tw-grid-rows-[repeat(auto,_auto)] tw-gap-2"
                id="search__elements">

                {% for item in items %}
                <a class="card" href="{{url_for('brands.find_by_slug', slug=item.slug)}}">
                    <div class="card-body tw-flex tw-flex-col tw-gap-1">
                        <img src="{{ item.path or '/static/images/generic.png' }}" alt="" class="img-card-top mb-2">
                        <p class="card-title tw-text-lg tw-font-semibold"> {{item.name}}</p>
                        <p class="card-text">{{item.description}}</p>
                    </div>
                </a>
                {% endfor %}



            </div>
            <div id="not-results">
                {% if items == [] %}
                <p class="tw-text-3xl tw-mt-4 tw-font-semibold tw-text-center">No results</p>
                {% endif %}
            </div>
            <!-- Pagination -->
            <div id="pagination" class="tw-mt-4"></div>
        </div>
    </div>


</form>
<!-- Pagination : EXPORT SCRIPT -->
<script>
    function setPaginationElement(pages, index) {
        console.log(pages, index)

        const paginationArea = document.getElementById('pagination');
        const pagesCount = Math.trunc(pages) <= 1 ? 1 : pages;
        index = index < 1 ? 1 : index;

        // Clear previous pagination
        paginationArea.innerHTML = '';

        // Create navigation structure
        const nav = document.createElement('nav');
        nav.setAttribute('aria-label', 'Page navigation example');
        nav.className = 'tw-flex tw-justify-center';

        const ul = document.createElement('ul');
        ul.className = 'pagination';

        // Previous button
        const prevLi = document.createElement('li');
        prevLi.className = `page-item ${index == 1 ? 'disabled' : ''}`;
        const prevLink = document.createElement('a');
        prevLink.className = 'page-link';
        prevLink.href = '#';
        prevLink.innerText = 'Previous';
        prevLink.addEventListener('click', () => {
            event.preventDefault()
            document.getElementById('input_page').value = index - 1; // Set the 
            document.getElementById('submit__search__button').click()
        })
        prevLi.appendChild(prevLink);
        ul.appendChild(prevLi);

        // Create page items
        for (let i = 0; i < pagesCount; i++) {
            const li = document.createElement('li');
            li.className = 'page-item';
            const link = document.createElement('a');
            link.className = `page-link ${index === i + 1 ? 'active' : ''}`;
            link.href = '#';
            link.innerText = i + 1;

            // Add click event listener
            link.addEventListener('click', function (event) {
                event.preventDefault(); // Prevent the default anchor behavior
                document.getElementById('input_page').value = i + 1; // Set the hidden input value
                document.getElementById('submit__search__button').click(); // Submit the form
            });

            li.appendChild(link);
            ul.appendChild(li);
        }

        // Next button
        const nextLi = document.createElement('li');
        nextLi.className = 'page-item';
        const nextLink = document.createElement('a');
        nextLink.className = `page-link ${index >= pagesCount ? 'disabled' : ''}`;
        nextLink.href = '#';
        nextLink.innerText = 'Next';
        nextLink.addEventListener('click', () => {
            event.preventDefault()
            document.getElementById('input_page').value = index + 1; // Set the 
            document.getElementById('submit__search__button').click()
        })
        nextLi.appendChild(nextLink);
        ul.appendChild(nextLi);

        // Append the list to the navigation
        nav.appendChild(ul);
        paginationArea.appendChild(nav);
    }
    setPaginationElement(`{{pages}}`, 1)
</script>

<!-- Requests -->
<script>
    async function getResults(e) {
        const brandSlug = `{{brand.slug}}`
        const page = e.page.value
        const toSearch = `name=${e.name.value}${e.filter.value ? '&filter=' + e.filter.value : ''}&json=1`
        const response = await fetch(`/brands/${brandSlug}/search/products?${toSearch}${page > 1 ? '&page=' + page : ''}`, {
            method: 'GET',
            headers: {
                'Content-Type': 'application/json'
            },
        })
        const content = await response.json();
        const data = content.data
        const cardContainer = document.getElementById('search__elements')
        cardContainer.innerHTML = '';
        const htmlContent = data.map(item => `<a class="card" href=../products/search/${item.slug}>
                                    
                    <div class="card-body tw-flex tw-flex-col tw-gap-1">
                        <img src="${item.path ?? '/static/images/generic.png'}" alt=""
                            class="img-card-top mb-2">
                        <p class="card-title tw-text-lg tw-font-semibold"> ${item.name}</p>
                        <p class="card-text">${item.description}</p>
                    </div>
                </a>`).join('')
        cardContainer.innerHTML = htmlContent;
        const noResultsContainer = document.getElementById('not-results')
        if (data.length > 0) {
            noResultsContainer.innerHTML = '';
            setPaginationElement(content.count, +page)
        } else {
            noResultsContainer.innerHTML = `<p class="tw-text-3xl tw-mt-4 tw-font-semibold tw-text-center">No results</p>`
            setPaginationElement(1, 1)

        }

        return false
    }
</script>
{% endblock %}

templates/search/bussiness_search.html
{% extends 'base.html' %}


{% block content %}

<div class="card tw-flex-tw-gap-3-tw-p-4 tw-w-full tw-h-1/3">
    <!-- --     Image -- -->
    <div class="card-body tw-w-full tw-h-1/3 tw-flex tw-items-center tw-justify-center">
        <img src="{{ bussiness.path or '/static/images/generic.png' }}" alt="{{ bussiness.name }}"
            class="card-img tw-w-1/4 tw-h-1/4">
        <!-- --     Description -- -->
        <div class="tw-w-2/3 tw-text-center">
            <h1 class="tw-text-2xl tw-font-bold">{{ bussiness.name }}</h1>
            <p class="tw-text-sm">{{ bussiness.description }}</p>
            <div>
                <a href="{{ url_for('ratings.find_by_bussiness', slug=bussiness.slug) }}"
                    class="tw-text-center tw-text-xs tw-text-blue-600 dark:tw-text-blue-500 hover:tw-underline tw-mt-[-5px]">View
                    Ratings</a>
                <a href="{{ url_for('bussiness.find_by_slug', slug=bussiness.slug) }}"
                    class="tw-text-center tw-text-xs tw-text-blue-600 dark:tw-text-blue-500 hover:tw-underline tw-mt-[-5px]">Back
                    to details</a>
            </div>

        </div>
    </div>
</div>

<form id="search__for" class="tw-flex tw-flex-col tw-w-full"
    onsubmit="event.preventDefault(); return getResults(this);">
    <div class="container tw-my-4 tw-flex tw-flex-col tw-w-full">
        <!-- Search bar -->
        <p class="tw-text-xl tw-mb-2">
            Enter something you're looking for </p>
        <div id="search__input" class="input-group mb-3">

            <button class="btn btn-primary" id="submit__search__button" type="submit">Search</button>

            <input type="text" name="name" value="{{keyword}}" class="form-control">
            <input type="number" name="page" id="input_page" hidden="true">
        </div>


    </div>
    <div class="tw-flex">
        <!-- Sidebar -->
        <div id="search__sidebar"
            class="bg-primary-subtle text-color-baseblue p-3 tw-w-1/5 tw-rounded-[10px] tw-min-w-min">
            <p class="tw-text-center tw-text-xl tw-font-semibold tw-m-3">Filters</p>
            <select class="form-select flex-grow" aria-label=".form-select-lg example" name="filter"
                id="filter__options">
                <option class="filter-option" value="" selected="selected">-- None --</option>
                <option class="filter-option" value="newest">Newest</option>
                <option class="filter-option" value="popular">Popular</option>
                <option class="filter-option" value="top_rated">Top Rated</option>


            </select>
        </div>
        <!-- Content -->
        <div id="search__container" class="tw-w-4/5 px-2">
            <!-- Elements -->

            <div class="tw-grid tw-grid-cols-[repeat(auto-fill,_minmax(200px,_1fr))] tw-grid-rows-[repeat(auto,_auto)] tw-gap-2"
                id="search__elements">

                {% for item in items %}
                <a class="card" href="{{url_for('products.find_by_slug', slug=item.slug )}}">
                    <div class="card-header tw-flex tw-justify-between">
                        <div>
                            <strong>{{item.price | round(2)}}$ USD</strong>
                        </div>
                        <div>
                            <strong>{{item.discount | round(1)}}% discount</strong>
                        </div>
                    </div>
                    <div class="card-body tw-flex tw-flex-col tw-gap-1">
                        <img src="{{ item.path or '/static/images/generic.png' }}" alt="" class="img-card-top mb-2">
                        <p class="card-title tw-text-lg tw-font-semibold"> {{item.name}}<span class="tw-font-normal">
                        </p>
                        <p class="card-text">{{item.description}}, <span
                                style="font-weight: bold;">{{item.quantity}}</span> in stock</p>
                    </div>
                    <div class="card-header tw-flex tw-justify-end">
                        <button href="" type="button" class="" id="{{item.stock_id}}"
                            onclick='event.preventDefault(); bookmarkButton(this)'>
                            {% if item.is_favorite > 0 %}
                            <img src='{{ url_for("static", filename="bootstrap-icons/bookmark-fill.svg") }}' value="1">
                            {% else %}
                            <img src='{{ url_for("static", filename="bootstrap-icons/bookmark.svg") }}' value="0">
                            {% endif %}
                        </button>
                    </div>
                </a>
                {% endfor %}

            </div>
            <div id="not-results">
                {% if items == [] %}
                <p class="tw-text-3xl tw-mt-4 tw-font-semibold tw-text-center">No results</p>
                {% endif %}
            </div>
            <!-- Pagination -->
            <div id="pagination" class="tw-mt-4"></div>
        </div>
    </div>


</form>
<!-- Pagination : EXPORT SCRIPT -->
<script>
    function setPaginationElement(pages, index) {

        const paginationArea = document.getElementById('pagination');
        const pagesCount = Math.trunc(pages) <= 1 ? 1 : pages;
        // Clear previous pagination
        paginationArea.innerHTML = '';

        // Create navigation structure
        const nav = document.createElement('nav');
        nav.setAttribute('aria-label', 'Page navigation example');
        nav.className = 'tw-flex tw-justify-center';

        const ul = document.createElement('ul');
        ul.className = 'pagination';

        // Previous button
        const prevLi = document.createElement('li');
        prevLi.className = `page-item ${index == 1 ? 'disabled' : ''}`;
        const prevLink = document.createElement('a');
        prevLink.className = 'page-link';
        prevLink.href = '#';
        prevLink.innerText = 'Previous';
        prevLink.addEventListener('click', () => {
            event.preventDefault()
            document.getElementById('input_page').value = index - 1; // Set the 
            document.getElementById('submit__search__button').click()
        })
        prevLi.appendChild(prevLink);
        ul.appendChild(prevLi);

        // Create page items
        for (let i = 0; i < pagesCount; i++) {
            const li = document.createElement('li');
            li.className = 'page-item';
            const link = document.createElement('a');
            link.className = `page-link ${index === i + 1 ? 'active' : ''}`;
            link.href = '#';
            link.innerText = i + 1;

            // Add click event listener
            link.addEventListener('click', function (event) {
                event.preventDefault(); // Prevent the default anchor behavior
                document.getElementById('input_page').value = i + 1; // Set the hidden input value
                document.getElementById('submit__search__button').click(); // Submit the form
            });

            li.appendChild(link);
            ul.appendChild(li);
        }

        // Next button
        const nextLi = document.createElement('li');
        nextLi.className = 'page-item';
        const nextLink = document.createElement('a');
        nextLink.className = `page-link ${index >= pagesCount ? 'disabled' : ''}`;
        nextLink.href = '#';
        nextLink.innerText = 'Next';
        nextLink.addEventListener('click', () => {
            event.preventDefault()
            document.getElementById('input_page').value = index + 1; // Set the 
            document.getElementById('submit__search__button').click()
        })
        nextLi.appendChild(nextLink);
        ul.appendChild(nextLi);

        // Append the list to the navigation
        nav.appendChild(ul);
        paginationArea.appendChild(nav);
    }
    setPaginationElement(`{{pages}}`, 1)
</script>

<!-- Requests -->
<script>
    async function getResults(e) {
        const bussinessSlug = `{{bussiness.slug}}`
        const page = e.page.value
        const toSearch = `name=${e.name.value}&filter=${e.filter.value}&json=1`
        const response = await fetch(`/bussiness/${bussinessSlug}/search/products?${toSearch}${page > 1 ? '&page=' + page : ''}`, {
            method: 'GET',
            headers: {
                'Content-Type': 'application/json'
            },
        })
        const content = await response.json();
        const data = content.data
        const cardContainer = document.getElementById('search__elements')
        cardContainer.innerHTML = '';
        const htmlContent = data.map(item => `<a class="card" href=../bussiness/search/${item.slug}>
                                    <div class="card-header tw-flex tw-justify-between">
                            <div>
                                <strong>${(item.price).toFixed(2)}$ USD</strong>
                            </div>
                            <div>
                                <strong>${(item.discount).toFixed(1)}% discount</strong>
                            </div>
                        </div>
                    <div class="card-body tw-flex tw-flex-col tw-gap-1">
                        <img src="${item.path ?? '/static/images/generic.png'}" alt=""
                            class="img-card-top mb-2">
                        <p class="card-title tw-text-lg tw-font-semibold"> ${item.name}</p>
                        <p class="card-text">${item.description}</p>
                    </div>
                </a>`).join('')
        cardContainer.innerHTML = htmlContent;
        const noResultsContainer = document.getElementById('not-results')
        if (data.length > 0) {
            noResultsContainer.innerHTML = '';
            setPaginationElement(content.count, +page)
        } else {
            noResultsContainer.innerHTML = `<p class="tw-text-3xl tw-mt-4 tw-font-semibold tw-text-center">No results</p>`
            setPaginationElement(1, 1)

        }

        return false
    }
</script>
<script>
    function bookmarkButton(button) {
        const item = button.querySelector('img')
        const isFavorite = item.getAttribute('value');
        const stockId = button.id
        const userId = "{{current_user.get_id()}}"
        console.log(stockId, isFavorite, userId)

        fetch(`/lists/${parseInt(isFavorite) ? 'remove' : 'add'}?stock_id=${stockId}&user_id=${userId}`, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json'
            },
        })
            .then(response => response.json())
            .then(data => {
                if (data[0]) {
                    if (isFavorite == 0) {
                        item.setAttribute('src', '{{ url_for("static", filename="bootstrap-icons/bookmark-fill.svg") }}')
                        item.setAttribute('value', 1)
                    } else {
                        item.setAttribute('src', '{{ url_for("static", filename="bootstrap-icons/bookmark.svg") }}')
                        item.setAttribute('value', 0)
                    }
                    alert('Success');
                } else {
                    console.log(data);
                    console.error('Error:', data.message);
                }
            });


    };
</script>
{% endblock %}