routes/brands_route.py
from flask import Blueprint, redirect, request, jsonify, render_template, session
from guard import role_required
from services.brands_service import *
from helpers import (
    filter_list,
    roles_list,
    slug_generator,
    type_list,
    set_pagination,
    generate_filename,
)
from services.products_service import (
    get_popular_by_brand as products_popular,
    get_newest_by_brand as produscts_newest,
    get_top_rated_by_brand as products_top_rated,
)
from services.bussiness_service import get_popular_by_brand as bussiness_popular
import bcrypt
from services.images_service import insert as insert_image, update as update_image

brands_bp = Blueprint("brands", __name__)

# BASIC DONE


@brands_bp.route("/test")
def index():
    return "Hello Brands!"


@brands_bp.route("/", methods=["GET"])
def find():
    id = request.args.get("id")
    response = get(id)
    return jsonify(response)


@brands_bp.route("/all", methods=["GET"])
def find_all():
    response = get_all()
    return jsonify(response)


@brands_bp.route("/", methods=["POST"])
@role_required("ADMIN")
def create():
    data = request.form
    image = request.files.get("image")
    image_name = generate_filename(image.filename)
    path = f"static/images/brands/{image_name}"
    response = insert(
        {
            "name": data.get("name"),
            "country": data.get("country"),
            "slug": slug_generator(data.get("name")),
        }
    )
    image.save(path)
    insert_image(image_name, response[0]["id"], "/" + path, "images_brands", "brand_id")
    return jsonify(response)


@brands_bp.route("/", methods=["PUT"])
@role_required("ADMIN")
def edit():
    data = request.form
    id = request.args.get("id")
    response = update(
        id,
        {
            "name": data.get("name"),
            "country": data.get("country"),
            "slug": slug_generator(data.get("name")),
        },
    )
    image = request.files.get("image")
    if image:
        image_name = generate_filename(image.filename)
        path = f"static/images/brands/{image_name}"
        image.save(path)
        update_image(
            image_name,
            response[0]["id"],
            "/" + path,
            "images_brands",
            "brand_id",
        )
    return jsonify(response)


@brands_bp.route("/", methods=["DELETE"])
def remove():
    id = request.args.get("id")
    response = delete(id)
    return "Success!"


@brands_bp.route("/", methods=["PATCH"])
def edit_status():
    status = request.get_json()["status"]
    id = request.args.get("id")
    response = update_status(id, status)
    return "Success!"


@brands_bp.route("/form", methods=["GET"])
def form():
    id = request.args.get("id", None)
    if id:
        brand = get(id)
    else:
        brand = [None]
    return render_template("form_create/form_create_brand.html", brand=brand)


@brands_bp.route("/edit/form", methods=["GET"])
def edit_form():
    return render_template("")


#################################################


@brands_bp.route("/<slug>/bussiness/")
def popular_bussines(slug):
    city = session.get("city")
    page = request.args.get("page", None)
    [start_pagination, end_pagination] = set_pagination(page)
    response = bussiness_popular(city, slug, start_pagination, end_pagination)
    return response


@brands_bp.route("/<slug>/search/products", methods=["GET"])
def find_by_product_filter(slug):
    page = request.args.get("page", None)
    filter = request.args.get("filter", "popular")
    json = request.args.get("json", False)
    name = request.args.get("name", "")
    if filter not in filter_list:
        return "error"
    brand = get_with_details(slug)
    [start_pagination, end_pagination] = set_pagination(page)
    if filter == "top_rated":
        [response, count] = products_top_rated(
            slug, False, start_pagination, end_pagination, word=name
        )
    elif filter == "popular":
        [response, count] = products_popular(
            slug, False, start_pagination, end_pagination, word=name
        )
    else:
        [response, count] = produscts_newest(
            slug, False, start_pagination, end_pagination, word=name
        )
    if json:
        return jsonify({"data": response, "count": count / 12})
    return render_template(
        "search/brand_search.html",
        items=response,
        brand=brand,
        count=count,
        pages=count / 12,
    )


@brands_bp.route("/search/<slug>", methods=["GET"])
def find_by_slug(slug):
    city = session.get("city")
    response = get_with_details(slug)
    [popular, count] = products_popular(slug, True)
    [top_rated, count] = products_top_rated(slug, True)
    [newest, count] = produscts_newest(slug, True)
    [bussiness, count] = bussiness_popular(city, slug, True)
    print("aaaa", response)
    return render_template(
        "details/detail_brand.html",
        brand=response,
        popular=popular,
        top_rated=top_rated,
        newest=newest,
        bussiness=bussiness,
    )


@brands_bp.route("/<status>", methods=["GET"])
def get_brands_by_status(status):
    if status not in status_list:
        return "error"
    name = request.args.get("name", "")
    page = request.args.get("page", None)
    [start_pagination, end_pagination] = set_pagination(page)
    [response, count] = get_by_status(status, start_pagination, end_pagination, name)
    print(response)
    return jsonify({"data": response, "count": count / 12})

routes/ratings_route.py
from flask import Blueprint, render_template, request, jsonify, session
from flask_login import current_user
from services.ratings_service import *
from services.bussiness_service import get_by_slug as get_bussiness
from services.products_service import get_by_slug as get_product
from helpers import set_pagination
from guard import secure_access

ratings_bp = Blueprint("ratings", __name__)


@ratings_bp.route("/", methods=["GET"])
def find():
    id = request.args.get("id")
    response = get(id)
    return jsonify(response)


@ratings_bp.route("/all", methods=["GET"])
def find_all():
    response = get_all()
    return jsonify(response)


@ratings_bp.route("/", methods=["POST"])
# @secure_access()
def create():
    data = request.get_json()
    score = data.get("score", None)
    comment = data.get("comment", None)
    product_id = data.get("product_id", None)
    bussiness_id = data.get("bussiness_id", None)
    user_id = current_user.get_id()
    if not user_id:
        return jsonify({"error": "User not found"}), 404
    response = insert_rating(user_id, bussiness_id, product_id, score, comment)
    return jsonify(response)


# @ratings_bp.route('/', methods=['PUT'])
# @secure_access()
# def edit():
#     id = request.args.get('id')
#     data = request.get_json()
#     response = update(id, data)
#     return jsonify(response)


@ratings_bp.route("/", methods=["DELETE"])
@secure_access()
def remove():
    id = request.args.get("id")
    response = delete(id)
    return jsonify(response)


@ratings_bp.route("/user", methods=["GET"])
@secure_access()
def find_by_user():
    user_id = current_user.get_id()
    response = get_by_user(user_id)
    return jsonify(response)


@ratings_bp.route("/bussiness/<slug>", methods=["GET"])
def find_by_bussiness(slug):
    page = request.args.get("page", None)
    lat = session.get("lat")
    lon = session.get("lon")
    [start_pagination, end_pagination] = set_pagination(page)
    bussiness = get_bussiness(slug, lat, lon)
    [response, count] = get_by_bussiness(
        int(bussiness["id"]), False, start_pagination, end_pagination
    )
    print(bussiness)
    return render_template(
        "ratings/ratings_bussiness.html",
        ratings=response,
        bussiness=bussiness,
        count=count,
        pages=count / 12,
    )


@ratings_bp.route("/product/<slug>", methods=["GET"])
def find_by_product(slug):
    page = request.args.get("page", None)
    [start_pagination, end_pagination] = set_pagination(page)
    product = get_product(slug)
    [response, count] = get_by_product(
        int(product["id"]), False, start_pagination, end_pagination
    )
    return render_template(
        "ratings/ratings_products.html",
        ratings=response,
        product=product,
        count=count,
        pages=count / 12,
    )


@ratings_bp.route("/<type>/<id>/aux", methods=["GET"])
def find_auxiliar(type, id):
    score = request.args.get("score")
    time = request.args.get("time")
    if score not in ["ASC", "DESC"]:
        ValueError("Undefined type")
    if time not in ["ASC", "DESC"]:
        ValueError("Undefined Filter")
    page = request.args.get("page")
    [start_pagination, end_pagination] = set_pagination(page)

    if type == "bussiness":
        [response, count] = get_by_bussiness(
            id, False, start_pagination, end_pagination, score, time
        )
    elif type == "products":
        [response, count] = get_by_product(
            id, False, start_pagination, end_pagination, score, time
        )
    else:
        ValueError("Type not valid")
    return jsonify({"data": response, "count": count / 12})  # 12 per page


# DESUSO


@ratings_bp.route("/bussiness/average", methods=["GET"])
def find_avg_by_bussiness():
    id = request.args.get("id")
    response = get_average_by_bussiness(id)
    return jsonify(response)


@ratings_bp.route("/product/average", methods=["GET"])
def find_avg_by_product():
    id = request.args.get("id")
    response = get_average_by_product(id)
    return jsonify(response)


@ratings_bp.route("/test", methods=["GET"])
def index():
    return "Hello Ratings!"

templates/details/detail_brand.html
{% extends 'base.html' %}

{% block content %}
<div class="tw-flex tw-flex-col tw-w-full">
    <!-- -- Brand details -- -->
    <div class="card tw-flex-tw-gap-3-tw-p-4 tw-w-full tw-h-1/3">
        <!-- --     Image -- -->
        <div class="card-body tw-flex-col tw-w-full tw-h-1/3 tw-flex tw-items-center tw-justify-center">
            <img src="{{ brand.path or '/static/images/generic.png' }}" alt="{{ brand.name }}"
                class="card-img tw-w-1/4 tw-h-1/4">
            <!-- --     Description -- -->
            <div class="tw-w-2/3 tw-text-center">
                <h1 class="tw-text-2xl tw-font-bold">{{ brand.name }}</h1>
                <p class="tw-text-sm">{{ brand.country }}</p>
            </div>
        </div>
    </div>
    <!-- -- Products -- -->
    <!-- --     Popular -- -->
    <div class="container tw-my-5">
        <div class="container-title tw-flex tw-gap-6">
            <h1 class="tw-font-semibold tw-text-4xl tw-mb-4 tw-inline-block">Popular products</h1>
            <div class="tw-inline-block tw-h-[3px] tw-grow tw-shrink tw-self-center tw-bg-baseblue">
            </div>
            <a class="btn btn-outline-primary tw-h-fit tw-self-center"
                href="{{ url_for('brands.find_by_product_filter', slug=brand.slug, filter='popular')}}">View More</a>
        </div>
        <div class="container tw-flex tw-gap-3">
            {% for item in popular %}
            <a class="card tw-grow tw-shrink tw-max-w-[25%] tw-min-w-[20%]"
                href="{{ url_for('products.find_by_slug', slug=item.slug) }}">
                <div class="card-body tw-flex tw-flex-col tw-gap-1">
                    <img src="{{ item.path or '/static/images/generic.png' }}" alt="" class="img-card-top mb-2">
                    <p class="card-title tw-text-lg tw-font-semibold">{{item.name}}</p>
                    <p class="card-text">{{item.description}}</p>
                </div>
            </a>
            {% endfor %}
        </div>
    </div>

    <!-- --     Top -- -->
    <div class="container tw-my-5">
        <div class="container-title tw-flex tw-gap-6">
            <h1 class="tw-font-semibold tw-text-4xl tw-mb-4 tw-inline-block">Top rated products</h1>
            <div class="tw-inline-block tw-h-[3px] tw-grow tw-shrink tw-self-center tw-bg-baseblue">
            </div>
            <a class="btn btn-outline-primary tw-h-fit tw-self-center"
                href="{{ url_for('brands.find_by_product_filter', slug=brand.slug, filter='top_rated')}}">View More</a>
        </div>
        <div class="container tw-flex tw-gap-3">
            {% for item in top_rated %}
            <a class="card tw-grow tw-shrink tw-max-w-[25%] tw-min-w-[20%]"
                href="{{ url_for('products.find_by_slug', slug=item.slug) }}">
                <div class="card-body tw-flex tw-flex-col tw-gap-1">
                    <img src="{{ item.path or '/static/images/generic.png' }}" alt="" class="img-card-top mb-2">
                    <p class="card-title tw-text-lg tw-font-semibold">{{item.name}}</p>
                    <p class="card-text">{{item.description}}</p>
                </div>
            </a>
            {% endfor %}
        </div>
    </div>


    <!-- --     New -- -->
    <div class="container tw-my-5">
        <div class="container-title tw-flex tw-gap-6">
            <h1 class="tw-font-semibold tw-text-4xl tw-mb-4 tw-inline-block">New products</h1>
            <div class="tw-inline-block tw-h-[3px] tw-grow tw-shrink tw-self-center tw-bg-baseblue">
            </div>
            <a class="btn btn-outline-primary tw-h-fit tw-self-center"
                href="{{ url_for('brands.find_by_product_filter', slug=brand.slug, filter='newest')}}">View More</a>
        </div>
        <div class="container tw-flex tw-gap-3">
            {% for item in newest %}
            <a class="card tw-grow tw-shrink tw-max-w-[25%] tw-min-w-[20%]"
                href="{{ url_for('products.find_by_slug', slug=item.slug) }}">
                <div class="card-body tw-flex tw-flex-col tw-gap-1">
                    <img src="{{ item.path or '/static/images/generic.png' }}" alt="" class="img-card-top mb-2">
                    <p class="card-title tw-text-lg tw-font-semibold">{{item.name}}</p>
                    <p class="card-text">{{item.description}}</p>
                </div>
            </a>
            {% endfor %}
        </div>
    </div>

    <!-- --     Pop Bussiness -- -->
    <div class="container tw-my-5">
        <div class="container-title tw-flex tw-gap-6">
            <h1 class="tw-font-semibold tw-text-4xl tw-mb-4 tw-inline-block">Popular Bussiness in your area</h1>
            <div class="tw-inline-block tw-h-[3px] tw-grow tw-shrink tw-self-center tw-bg-baseblue">
            </div>
            <a class="btn btn-outline-primary tw-h-fit tw-self-center"
                href="{{ url_for('brands.popular_bussines', slug=brand.slug)}}">View More</a>
        </div>
        <div class="container tw-flex tw-gap-3">
            {% for item in bussiness %}
            <a class="card tw-grow tw-shrink tw-max-w-[25%] tw-min-w-[20%]"
                href="{{ url_for('bussiness.find_by_slug', slug=item.slug) }}">
                <div class="card-body tw-flex tw-flex-col tw-gap-1">
                    <img src="{{ item.path or '/static/images/generic.png' }}" alt="" class="img-card-top mb-2">
                    <p class="card-title tw-text-lg tw-font-semibold">{{item.name}}</p>
                    <p class="card-text">{{item.description}}</p>
                </div>
            </a>
            {% endfor %}
        </div>
    </div>

    <div class="tw-flex tw-w-full tw-m-4 tw-justify-center tw-items-center">
        <a href="{{url_for('brands.find_by_product_filter', slug=brand.slug)}}" class="btn btn-primary btn-large">View
            more
            products of this brand</a>
    </div>

</div>
{% endblock %}

templates/details/detail_product.html
{% extends 'base.html' %}

{% block content %}
<div class="tw-flex tw-flex-col tw-w-full">
    {% if product.status == "IN REVIEW" %}
    <div class="alert alert-warning tw-mb-2">
        <strong>Warning!</strong> This product is in review, please check back later.
    </div>
    {% elif product.status == "REJECTED" %}
    <div class="alert alert-danger tw-mb-2">
        <strong>Warning!</strong> This product has been rejected, please contact support.
    </div>
    {% endif %}
    <!-- -- Products details -- -->
    <div class="card tw-flex-tw-gap-3-tw-p-4 tw-w-full tw-h-1/3">
        <!-- --     Image -- -->
        <div class="card-body tw-w-full tw-h-1/3 tw-flex tw-items-center tw-justify-center">
            <img src="{{ product.path or '/static/images/generic.png' }}" alt="{{ product.name }}"
                class="card-img tw-w-1/4 tw-h-1/4">
            <!-- --     Description -- -->
            <div class="tw-w-2/3 tw-text-center">
                <h1 class="tw-text-2xl tw-font-bold">{{ product.name }}</h1>
                <p class="tw-text-sm">{{ product.description }}</p>
                <div>
                    <div class="rating" id="rating">
                        <span class="star" data-value="1">&#9733;</span>
                        <span class="star" data-value="2">&#9733;</span>
                        <span class="star" data-value="3">&#9733;</span>
                        <span class="star" data-value="4">&#9733;</span>
                        <span class="star" data-value="5">&#9733;</span>
                    </div>
                    <a href="{{ url_for('ratings.find_by_product', slug=product.slug) }}"
                        class="tw-text-center tw-text-xs tw-text-blue-600 dark:tw-text-blue-500 hover:tw-underline tw-mt-[-5px]">View
                        More Ratings</a>
                </div>
                <div class="tw-flex tw-justify-evenly tw-mt-2 tw-gap-4 ">
                    <div class="tw-flex tw-flex-col tw-justify-evenly">
                        <div>
                            <p>Average</p>
                            <p class="tw-font-bold" id="average">{{ rating.avg_score | round(0) }}</p>
                        </div>
                        <div class="tw-mt-2">
                            <p>Brand</p>
                            <a class="tw-font-bold tw-text-black"
                                href="{{url_for('brands.find_by_slug', slug=brand.slug)}}">{{ brand.name
                                }}</a>
                        </div>

                    </div>
                    <div class="tw-flex tw-justify-evenly tw-flex-col">
                        <p>Favorite Count</p>
                        <p class="tw-font-bold" id="fav-count">{{product.fav_count}}</p>
                    </div>
                    <div class="tw-flex tw-justify-evenly tw-flex-col">

                        <div>
                            <p>Reviews</p>
                            <p class="tw-font-bold" id="count">{{rating.count}}</p>
                        </div>
                        <div class="tw-mt-2">
                            <p>Country</p>
                            <p class="tw-font-bold">{{brand.country}}</p>
                        </div>
                    </div>

                </div>

            </div>
        </div>

    </div>

    <!-- -- Bussiness Nearest -- -->
    <div class="container tw-my-5">
        <div class="container-title tw-flex tw-gap-6">
            <h1 class="tw-font-semibold tw-text-4xl tw-mb-4 tw-inline-block">Nearest Bussiness with this product</h1>
            <div class="tw-inline-block tw-h-[3px] tw-grow tw-shrink tw-self-center tw-bg-baseblue">
            </div>
            <a class="btn btn-outline-primary tw-h-fit tw-self-center"
                href="{{ url_for('products.find_by_bussiness_filter', slug=product.slug, filter='nearest')}}">View
                More</a>
        </div>
        <div class="container tw-flex tw-gap-3">
            {% for item in bussiness_by_distance %}
            <a class="card tw-grow tw-shrink tw-max-w-[25%] tw-min-w-[20%]"
                href="{{ url_for('bussiness.find_by_slug', slug=item.slug) }}">
                <div class="card-header tw-flex tw-justify-between">
                    <div>
                        <strong>{{item.price | round(2)}}$ USD</strong>
                    </div>
                    <div>
                        <strong>{{item.distance | round(1)}} Km away</strong>
                    </div>
                </div>
                <div class="card-body tw-flex tw-flex-col tw-gap-1">
                    <img src="{{ item.path or '/static/images/generic.png' }}" alt="" class="img-card-top mb-2">
                    <p class="card-title tw-text-lg tw-font-semibold">{{item.name}}</p>
                    <p class="card-text">{{item.description}}, <span style="font-weight: bold;">{{item.quantity}}</span>
                        in stock</p>
                </div>
            </a>
            {% endfor %}
        </div>
    </div>

    <!-- -- Bussiness Cheapest -- -->
    <div class="container tw-my-5">
        <div class="container-title tw-flex tw-gap-6">
            <h1 class="tw-font-semibold tw-text-4xl tw-mb-4 tw-inline-block"> Bussiness with this product by price</h1>
            <div class="tw-inline-block tw-h-[3px] tw-grow tw-shrink tw-self-center tw-bg-baseblue">
            </div>
            <a class="btn btn-outline-primary tw-h-fit tw-self-center"
                href="{{ url_for('products.find_by_bussiness_filter', slug=product.slug, filter='cheapest',)}}">View
                More</a>
        </div>
        <div class="container tw-flex tw-gap-3">
            {% for item in bussiness_by_price %}
            <a class="card tw-grow tw-shrink tw-max-w-[25%] tw-min-w-[20%]"
                href="{{ url_for('bussiness.find_by_slug', slug=item.slug) }}">
                <div class="card-header tw-flex tw-justify-between">
                    <div>
                        <strong>{{item.price | round(2)}}$ USD</strong>
                    </div>
                    <div>
                        <strong>{{item.discount | round(2)}}% discount</strong>
                    </div>
                </div>
                <div class="card-body tw-flex tw-flex-col tw-gap-1">
                    <img src="{{ item.path or '/static/images/generic.png' }}" alt="" class="img-card-top mb-2">
                    <p class="card-title tw-text-lg tw-font-semibold">{{item.name}}</p>
                    <p class="card-text">{{item.description}}, <span style="font-weight: bold;">{{item.quantity}}</span>
                        in stock</p>
                </div>
            </a>
            {% endfor %}
        </div>
        <div class="tw-flex tw-w-full tw-m-4 tw-justify-center tw-items-center">
            <a href="{{url_for('products.bussiness_by_products', slug=product.slug)}}"
                class="btn btn-primary btn-large">View more
                bussiness with this
                products</a>
        </div>
    </div>

    <script>
        const stars = document.querySelectorAll('.star');
        const countDisplay = document.getElementById('count');
        let average = parseFloat(document.getElementById('average').innerHTML);
        let scoreCount = '{{ rating.count }}' | 0;

        function updateStars(rating) {
            stars.forEach(star => {
                star.classList.remove('filled');
                if (star.dataset.value <= rating) {
                    star.classList.add('filled');
                }
            });
        }
        updateStars(average);

        stars.forEach(star => {
            star.addEventListener('mouseover', () => {
                updateStars(star.dataset.value);
            });

            star.addEventListener('mouseout', () => {
                updateStars(average);
            });

            star.addEventListener('click', async () => {
                const result = await fetch('/ratings', {
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/json'
                    },
                    body: JSON.stringify({
                        product_id: '{{ product.id }}',
                        score: star.dataset.value
                    })
                });
                if (result.ok) {
                    const count = `{{ rating.count }}`
                    const data = await result.json()
                    updateStars(data.avg)
                    document.getElementById('average').innerHTML = data.avg.toFixed(1);
                    average = data.avg;
                    document.getElementById('count').innerHTML = data.count;
                    alert(`Rating ${data.count == count ? 'Updated' : 'Created'}`);
                } else {
                    alert('Error saving rating');
                }

            });
        });
    </script>
    {% endblock %}