routes/admin_route.py
from flask import Blueprint, redirect, request, jsonify, session, render_template
from guard import login_required
from services.stats_service import (
    bussiness_stats as bussiness,
    products_stats as products,
    tags_stats as tags,
    users_stats as users,
)
from helpers import set_pagination, status_list, type_list, roles_list
from services.products_service import get_by_status as products_by_status
from services.bussiness_service import get_by_status as bussinnes_by_status
from services.tags_service import get_by_status as tags_by_status
from services.users_service import (
    get as get_user,
    update_role,
    update as update_user,
)
from flask_login import current_user

# TODO: Protect
admin_bp = Blueprint("admin", __name__)


@admin_bp.route("/", methods=["GET"])
def stats():
    bussiness_stats = bussiness()
    users_stats = users()
    products_stats = products()
    tags_stats = tags()
    return render_template(
        "dashboards/admin_dashboard.html",
        bussiness=bussiness_stats,
        users=users_stats,
        products=products_stats,
        tags=tags_stats,
    )


@admin_bp.route("/search", methods=["GET"])
def general_search():

    type = request.args.get("type", "products")
    [start_pagination, end_pagination] = set_pagination(None)
    if type == "products":
        [response, count] = products_by_status(
            "approved", start_pagination, end_pagination, ""
        )
    elif type == "bussiness":
        [response, count] = bussinnes_by_status(
            "approved", start_pagination, end_pagination, ""
        )
    elif type == "tags":
        [response, count] = tags_by_status(
            "approved", start_pagination, end_pagination, ""
        )
    else:
        [response, count] = products_by_status(  # users by status
            "approved", start_pagination, end_pagination, ""
        )

    return render_template(
        "search/admin_search.html",
        items=response,
        pages=count / 12,  # 12 per page
    )


@admin_bp.route("/profile-edit", methods=["GET"])
def edit_profile_from_admin():
    id = request.args.get("id")
    response = get_user(id)
    return render_template("admin/edit_user.html", user=response)


@admin_bp.route("/edit-user", methods=["PUT"])
def update_profile_from_admin():
    data = request.get_json()
    id = request.args.get("id")
    if data.get("role") not in roles_list:
        return "Role not found", 400
    update_user(id, data)
    update_role(id, data.get("role"))
    return "Success!"


@admin_bp.before_request
@login_required()
def before_request():
    if not current_user.has_role("ADMIN"):
        return redirect("/unauthorized")

routes/auth_route.py
from flask import Blueprint, render_template, request, jsonify, Response
from guard import *
from helpers import roles_list, regex_password_match
from services.auth_service import *
from services.lists_services import insert as create_list

auth_bp = Blueprint("auth", __name__)


@auth_bp.route("/")
@role_required(roles_list["admin"])
def index():
    return "Hello Auth!"


@auth_bp.route("/register", methods=["POST"])
def user_register():
    data = request.get_json()
    password = data.get("password")
    if password != data.get("confirm-password"):
        return "Password does not match", 400
    if verify_existing_email(data.get("email")):
        return "Email already exists", 400
    verify_password(password)
    register_data = register(data)
    create_list(register_data.get("id"))
    return "Success!"


@auth_bp.route("/login", methods=["POST"])
def user_login():
    data = request.get_json()
    verify_password(data.get("password"))
    response = login(data["email"], data["password"])
    if isinstance(response, ValueError):
        return response.args[0], 400
    return "Success!", 200


@auth_bp.route("/password", methods=["PUT"])
def edit_password():
    id = current_user.get_id() or 3
    data = request.get_json()
    password = data.get("password")
    if password != data.get("confirm-password"):
        return "Password does not match", 400
    update_password(id, password)
    return "Success!"


@auth_bp.route("/logout", methods=["GET"])
@login_required()
def user_logout():
    logout()
    return "Success!", 200


@auth_bp.route("/register", methods=["GET"])
def register_form():
    return render_template("auth/register.html")


@auth_bp.route("/login", methods=["GET"])
def login_form():
    return render_template("auth/login.html")


def verify_password(password):
    if len(password) > 12 or len(password) < 8:
        return "Password must be 8-12 character long", 400
    regex_result = regex_password_match(password)
    if regex_result != True:
        return regex_result, 400

routes/lists_route.py
from flask import Blueprint, render_template, request, jsonify
from services.lists_services import *
from guard import *

lists_bp = Blueprint("lists", __name__)


@lists_bp.route("/test")
def index():
    return "Hello Lists!"


@lists_bp.route("/", methods=["GET"])
def find():
    id = request.args.get("id")
    response = get(id)
    return jsonify(response)


@lists_bp.route("/all", methods=["GET"])
def find_all():
    response = get_all()
    return jsonify(response)


@lists_bp.route("/", methods=["POST"])
def create():
    data = request.get_json()
    response = insert(data)
    return jsonify(response)


# @lists_bp.route('/', methods=['PUT'])
# def edit():
#     id = request.args.get('id')
#     data = request.get_json()
#     response = update(id, data)
#     print(response)
#     return 'Hello Lists!'


@lists_bp.route("/", methods=["DELETE"])
@secure_access()
def remove():
    id = request.args.get("id")
    response = delete(id)
    return jsonify(response)


@lists_bp.route("/add", methods=["POST"])
@secure_access()
def add_product():
    list_by_user = get_id_by_user(current_user.get_id())
    id = list_by_user[0].get("list_id")
    stock_id = request.args.get("stock_id")
    print(stock_id, id)
    response = insert_product(id, stock_id)
    print(response)
    return jsonify(response)


@lists_bp.route("/remove", methods=["POST"])
@secure_access()
def remove_product():
    list_by_user = get_id_by_user(current_user.get_id())
    id = list_by_user[0].get("list_id")
    stock_id = request.args.get("stock_id")
    response = delete_product(id, stock_id)
    return jsonify(response)


@lists_bp.route("/user", methods=["GET"])
@secure_access()
def find_by_user():
    id = current_user.get_id()
    [response, count] = get_by_user(id)
    return render_template(
        "lists/list.html", list=response, count=count, pages=count / 12
    )

routes/owner_route.py
from flask import Blueprint, request, render_template, redirect, jsonify
from guard import *
from flask_login import current_user
from helpers import roles_list, set_pagination, filter_list
from services.products_service import (
    get_popular_by_owner as products_popular,
    get_top_rated_by_owner as products_top_rated,
)
from services.brands_service import *
from services.bussiness_service import (
    get_by_owner_popular as bussiness_popular,
    get_by_owner as bussiness_all,
    get_by_owner_top_rated as bussiness_top_rated,
)
from services.stocks_service import get_by_bussiness as stock_bussiness

owner_bp = Blueprint("owner", __name__)


@owner_bp.route("/dashboard", methods=["GET"])
def main():
    owner = current_user.get_id() or 3
    [popular_products, count] = products_popular(owner, limited=True)
    [popular_bussiness, count] = bussiness_popular(owner, limited=True)
    [unpopular_bussiness, count] = bussiness_popular(owner, limited=True, order="ASC")
    [unpopular_products, count] = products_popular(owner, limited=True, order="ASC")
    [top_rated_bussiness, count] = bussiness_top_rated(owner, limited=True)
    [top_rated_products, count] = products_top_rated(owner, limited=True)
    [less_rated_bussiness, count] = bussiness_top_rated(
        owner, limited=True, order="ASC"
    )
    [less_rated_products, count] = products_top_rated(owner, limited=True, order="ASC")
    # print("wut")
    # print(popular_products)
    return render_template(
        "/dashboards/owner_dashboard.html",
        popular_products=popular_products,
        popular_bussiness=popular_bussiness,
        less_rated_products=less_rated_products,
        top_rated_products=top_rated_products,
        unpopular_bussiness=unpopular_bussiness,
        unpopular_products=unpopular_products,
        top_rated_bussiness=top_rated_bussiness,
        less_rated_bussiness=less_rated_bussiness,
    )
    # return render_template('',
    #                        popular_products=popular_products, popular_bussiness=popular_bussiness,
    #                        unpopular_bussiness=unpopular_bussiness)


@owner_bp.route("/search", methods=["GET"])
def general_search():
    owner_id = current_user.get_id()
    type = request.args.get("type", "products")
    filter = request.args.get("filter", "popular")
    [start_pagination, end_pagination] = set_pagination(None)
    if type == "products":
        if filter == "popular":
            print("OWNER ID", owner_id)
            [response, count] = products_popular(
                owner_id, False, start_pagination, end_pagination
            )
        elif filter == "top_rated":
            [response, count] = products_top_rated(
                owner_id, False, start_pagination, end_pagination
            )
        elif filter == "less_rated":
            [response, count] = products_top_rated(
                owner_id, False, start_pagination, end_pagination, order="ASC"
            )
        elif filter == "unpopular":
            [response, count] = products_popular(
                owner_id, False, start_pagination, end_pagination, order="ASC"
            )
    elif type == "bussiness":
        if filter == "popular":
            [response, count] = bussiness_popular(
                owner_id, False, start_pagination, end_pagination
            )
        elif filter == "top_rated":
            [response, count] = bussiness_top_rated(
                owner_id, False, start_pagination, end_pagination
            )
        elif filter == "less_rated":
            [response, count] = bussiness_top_rated(
                owner_id, False, start_pagination, end_pagination, order="ASC"
            )
        elif filter == "unpopular":
            [response, count] = bussiness_popular(
                owner_id, False, start_pagination, end_pagination, order="ASC"
            )

    return render_template(
        "search/owner_search.html",
        items=response,
        pages=count / 12,  # 12 per page
    )


@owner_bp.route("/bussiness/popular", methods=["GET"])
def popular_bussiness():
    page = request.args.get("page", None)
    name = request.args.get("name", "")
    status = request.args.get("status", None)
    if status not in status_list:
        return "error"
    owner = current_user.get_id()
    [start_pagination, end_pagination] = set_pagination(page)
    [response, count] = bussiness_popular(
        owner,
        start_page=start_pagination,
        end_page=end_pagination,
        order="ASC",
        word=name,
        status=status,
    )
    return jsonify({"data": response, "count": count / 12})
    # return render_template('', bussiness=response)


@owner_bp.route("/bussiness/unpopular", methods=["GET"])
def unpopular_bussiness():
    page = request.args.get("page", None)
    name = request.args.get("name", "")
    status = request.args.get("status", None)
    if status not in status_list:
        return "error"
    owner = current_user.get_id()
    [start_pagination, end_pagination] = set_pagination(page)
    [response, count] = bussiness_popular(
        owner,
        start_page=start_pagination,
        end_page=end_pagination,
        word=name,
        status=status,
    )
    return jsonify({"data": response, "count": count / 12})

    # return render_template('', bussiness=response)


@owner_bp.route("/products/popular", methods=["GET"])
def popular_products():
    page = request.args.get("page", None)
    name = request.args.get("name", "")
    status = request.args.get("status", None)
    if status not in status_list:
        return "error"
    owner = current_user.get_id()
    [start_pagination, end_pagination] = set_pagination(page)
    [response, count] = products_popular(
        owner,
        start_page=start_pagination,
        end_page=end_pagination,
        word=name,
        status=status,
    )
    return jsonify({"data": response, "count": count / 12})

    # return render_template('', products=response)


@owner_bp.route("/bussiness/less_rated", methods=["GET"])
def less_rated_bussiness():
    page = request.args.get("page", None)
    name = request.args.get("name", "")
    status = request.args.get("status", None)
    if status not in status_list:
        return "error"
    owner = current_user.get_id()
    [start_pagination, end_pagination] = set_pagination(page)
    [response, count] = bussiness_top_rated(
        owner,
        start_page=start_pagination,
        end_page=end_pagination,
        order="ASC",
        word=name,
        status=status,
    )
    return jsonify({"data": response, "count": count / 12})

    # return render_template('', products=response)


@owner_bp.route("/bussiness/top_rated", methods=["GET"])
def top_rated_bussiness():
    page = request.args.get("page", None)
    name = request.args.get("name", "")
    status = request.args.get("status", None)
    if status not in status_list:
        return "error"
    owner = current_user.get_id()
    [start_pagination, end_pagination] = set_pagination(page)
    [response, count] = bussiness_top_rated(
        owner,
        start_page=start_pagination,
        end_page=end_pagination,
        word=name,
        status=status,
    )
    return jsonify({"data": response, "count": count / 12})

    # return render_template('', products=response)


@owner_bp.route("/products/top_rated", methods=["GET"])
def top_rated_products():
    page = request.args.get("page", None)
    name = request.args.get("name", "")
    status = request.args.get("status", None)
    if status not in status_list:
        return "error"
    owner = current_user.get_id()
    [start_pagination, end_pagination] = set_pagination(page)
    [response, count] = products_top_rated(
        owner,
        start_page=start_pagination,
        end_page=end_pagination,
        word=name,
        status=status,
    )
    return jsonify({"data": response, "count": count / 12})

    # return render_template('', products=response)


@owner_bp.route("/products/less_rated", methods=["GET"])
def less_rated_products():
    page = request.args.get("page", None)
    name = request.args.get("name", "")
    status = request.args.get("status", None)
    if status not in status_list:
        return "error"
    owner = current_user.get_id()
    [start_pagination, end_pagination] = set_pagination(page)
    [response, count] = products_top_rated(
        owner,
        start_page=start_pagination,
        end_page=end_pagination,
        order="ASC",
        word=name,
        status=status,
    )
    return jsonify({"data": response, "count": count / 12})

    # return render_template('', products=response)


@owner_bp.route("/products/unpopular", methods=["GET"])
def unpopular_products():
    page = request.args.get("page", None)
    name = request.args.get("name", "")
    status = request.args.get("status", None)
    if status not in status_list:
        return "error"
    owner = current_user.get_id()
    [start_pagination, end_pagination] = set_pagination(page)
    [response, count] = products_popular(
        owner,
        start_page=start_pagination,
        end_page=end_pagination,
        order="ASC",
        word=name,
        status=status,
    )
    return jsonify({"data": response, "count": count / 12})

    # return render_template('', products=response)


@owner_bp.route("/<slug>/stocks", methods=["GET"])
def stocks(slug):
    owner = current_user.get_id()
    page = request.args.get("page", None)
    name = request.args.get("name", "")
    status = request.args.get("status", None)
    if status not in status_list:
        return "error"
    [start_pagination, end_pagination] = set_pagination(page)
    [response, count] = stock_bussiness(slug, owner, start_pagination, end_pagination)
    return jsonify({"data": response, "count": count / 12})

    # return render_template('', stocks=response)


@owner_bp.before_request
@login_required()
def before_request():
    if not current_user.has_role("OWNER"):

templates/base.html
<!DOCTYPE html>
<html lang="en" class="tw-h-full">

</html>

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='bootstrap/css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/tailwind-output.css') }}">
    <script src="{{ url_for('static', filename='bootstrap/js/bootstrap.bundle.min.js') }}"></script>
    {% if not session['city'] and not session['location_requested'] %}
    <script>
        function geoFindMe() {
            async function success(position) {
                // Send data and keep navigating
                const latitude = position.coords.latitude;
                const longitude = position.coords.longitude;

                const response = await fetch('/handle_location', {
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/json'
                    },
                    body: JSON.stringify({ latitude: latitude, longitude: longitude })
                })
                if (response.status == 201) {
                    window.location.href = '/dashboard'
                    return
                } else {
                    window.location.href = '/error'
                }
            }

            function error() {
                // Redirect to allow location
                window.location.href = '/allow-location'
            }

            if (!navigator.geolocation) {
                // Alert warning // exit somewhere
                alert("Geolocation is not supported by your browser")
            } else {
                navigator.geolocation.getCurrentPosition(success, error);
            }
        }
        geoFindMe()
    </script>
    {% endif %}
</head>

<body class="tw-position-relative tw-min-h-full tw-flex tw-flex-col">
    {% if loading %}
    {% include 'misc/loading_spinner.html' %}
    {% block loading %}
    {% endblock %}
    {% endif %}
    {% include 'navbar.html' %}
    {% block navbar %}
    {% endblock %}
    <div
        class="jumbotron tw-py-8 tw-px-3 tw-h-full tw-font-sans tw-bg-slate-100 tw-grow tw-shrink tw-flex tw-content-center tw-items-center tw-flex-col">

        {% block content %}
        {% endblock %}
    </div>
    {% include 'footer.html' %}
    {% block footer %}
    {% endblock %}
</body>

</html>

templates/footer.html
{% block footer %}

<footer class="text-primary vh-50 container-fluid bg-primary-subtle w-100 p-4">
    <div class="row">
        <div class="col">
            <p class="fs-4 fw-light">About Us</p>
            <p class="fs-6 fw-light">Promo Radar is a project made from the people to the people. Looking foward to
                make
                the life a little
                bit easier. </p>
        </div>
        <div class="col">
            <p class="fs-4 fw-light">Frecuent Questions</p>
            <ul class="list-inline">
                <li> <a href="#" class="fw-light text-decoration-none">
                        Why you made this project?
                    </a></li>
                <li>
                    <a href="#" class="fw-light text-decoration-none">
                        What inspired you to make this?
                    </a>
                </li>
                <li>
                    <a href="#" class="fw-light text-decoration-none">Who paid for this
                        project?</a>
                </li>
                <li><a href="#" class="fw-light text-decoration-none">Which is your next
                        step?</a></li>

            </ul>
        </div>
        <div class="col">
            <p class="fs-4 fw-light">Contact Us</p>
            <div class="list-inline d-flex flex-column justify-content-around" style="height: 65%;">

                <a class="nav-link active" aria-current="page" href="#">
                    <img src="{{ url_for('static', filename='bootstrap-icons/envelope.svg') }}" alt="Logo" width="24"
                        height="18" class="d-inline-block text-light mb-1">
                    client-services@promoradar.org
                </a>

                <a class="nav-link active" aria-current="page" href="#">
                    <img src="{{ url_for('static', filename='bootstrap-icons/twitter-x.svg') }}" alt="Logo" width="24"
                        height="18" class="d-inline-block text-light mb-1">
                    @promoradar
                </a>

                <a class="nav-link active" aria-current="page" href="#">
                    <img src="{{ url_for('static', filename='bootstrap-icons/telephone.svg') }}" alt="Logo" width="24"
                        height="18" class="d-inline-block text-light mb-1">
                    +(305)446-24-66
                </a>
            </div>
        </div>
    </div>

</footer>

{% endblock %}

templates/navbar.html
{% block navbar %}

<nav class="navbar navbar-dark navbar-expand-lg bg-primary bg-gradient">
    <div class="container-fluid pl-2">
        <a class="navbar-brand" href="/">
            <img src="{{ url_for('static', filename='images/logo.png') }}" alt="Logo" width="45" height="40"
                class="d-inline-block align-text-top">
            <span class="align-middle ms-2">Promo Radar</span>
        </a>

        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

    </div>
    <div class="container-fluid">
        <div class="collapse navbar-collapse navbarSupportedContent just">
            <ul class="navbar-nav m-auto mb-2 mb-lg-0">
                <li class="nav-item d-flex align-items-center">

                    <a class="nav-link active" aria-current="page" href="/">
                        <img src="{{ url_for('static', filename='bootstrap-icons/house-fill.svg') }}" alt="Logo"
                            width="24" height="18" class="d-inline-block text-light mb-1">
                        Home
                    </a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle active" href="#" role="button" data-bs-toggle="dropdown"
                        aria-expanded="false">
                        <img src="{{ url_for('static', filename='bootstrap-icons/search.svg') }}" alt="Logo" width="24"
                            height="18" class="d-inline-block text-light mb-1">
                        Search
                    </a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="{{url_for('search.general_search')}}">
                                <img src="{{ url_for('static', filename='bootstrap-icons/gift-fill.svg') }}" alt="Logo"
                                    width="20" height="15" class="d-inline-block mb-1">
                                Producs</a></li>
                        <li><a class="dropdown-item" href="{{ url_for('search.general_search', type='bussiness')}}">
                                <img src="{{ url_for('static', filename='bootstrap-icons/building-fill.svg') }}"
                                    alt="Logo" width="20" height="15" class="d-inline-block mb-1">
                                Bussiness</a></li>
                    </ul>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle active" href="#" role="button" data-bs-toggle="dropdown"
                        aria-expanded="false">
                        <img src="{{ url_for('static', filename='bootstrap-icons/person-fill.svg') }}" alt="Logo"
                            width="24" height="18" class="d-inline-block text-light mb-1">
                        Profile
                    </a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item"
                                href="{{url_for('lists.find_by_user', user_id=current_user.get_id())}}">
                                <img src="{{ url_for('static', filename='bootstrap-icons/star.svg') }}" alt="Logo"
                                    width="20" height="15" class="d-inline-block mb-1">
                                My List</a></li>
                        <li><a class="dropdown-item" href="{{ url_for('users.edit_profile') }}">
                                <img src="{{ url_for('static', filename='bootstrap-icons/list-ul.svg') }}" alt="Logo"
                                    width="20" height="15" class="d-inline-block mb-1">
                                My Profile</a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
    <div class="container-fluid">
        <div class="justify-content-end collapse navbar-collapse navbarSupportedContent">
            <ul class="navbar-nav mb-2 mb-lg-0">
                {% if current_user.is_authenticated %}
                <li class="nav-item">
                    <button class="nav-link active" aria-current="page" onclick="event.preventDefault(); logout()">Log
                        Out</button>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{{url_for('auth.user_register')}}">Sign
                        In</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{{url_for('auth.user_login')}}">Log In</a>
                </li>
                {% endif %}
                {% if current_user.role == "CLIENT"%}
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="#">Become Owner</a>
                </li>
                {% endif %}
                {% if current_user.role == "OWNER" %}
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{{url_for('owner.main')}}">Owner
                        Dashboard</a>
                </li>
                {% endif %}
                {% if current_user.role == "ADMIN"%}
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{{url_for('admin.stats')}}">Admin
                        Dashboard</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>
<script>
    async function logout() {
        await fetch('/auth/logout', {
            method: 'GET',
            headers: {
                'Content-Type': 'application/json'
            }
        })
            .then(res => res.text())
            .then(data => {
                alert(data)
                window.location.href = '/';
            })
            .catch(err => {
                console.log(err);
            })
    }
</script>
{% endblock %}

templates/questions.html
{% extends "base.html"%}

{% block content %}


<div class="container-fluid">
    <h2 class="m-2">Frecuent Asked Questions</h2>
    <div class="card m-2">
        <div class="card-body">
            <div class="card-title fs-4 text-primary fw-light">
                Why you made this project?
            </div>
            <div class="card-text">
                Lorem ipsum dolor sit, amet consectetur adipisicing elit. Libero ex reiciendis fuga laudantium officia
                est quibusdam ad dignissimos, nemo aliquam tenetur alias! Iure asperiores dicta maiores excepturi atque
                sapiente laborum.
            </div>
        </div>
    </div>
    <div class="card m-2">
        <div class="card-body">
            <div class="card-title fs-4 text-primary fw-light">
                What inspired you to make this?
            </div>
            <div class="card-text">
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet laboriosam repellat possimus natus saepe
                aliquid, praesentium commodi sequi corporis consequuntur. Suscipit dignissimos facere sit placeat
                quibusdam distinctio? Quisquam, quos. Architecto.
            </div>
        </div>
    </div>
    <div class="card m-2">
        <div class="card-body">
            <div class="card-title fs-4 text-primary fw-light">
                Who paid for this project?
            </div>
            <div class="card-text">
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum delectus eveniet repudiandae
                molestias omnis ullam blanditiis sequi odio explicabo maiores, nobis aliquam nulla quas praesentium sint
                ipsum laborum ab aut.
            </div>
        </div>
    </div>
    <div class="card m-2">
        <div class="card-body">
            <div class="card-title fs-4 text-primary fw-light">
                Which is your next step?
            </div>
            <div class="card-text">
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Earum, obcaecati amet officia saepe quaerat at
                tempora nostrum expedita quidem nobis ratione quas velit temporibus molestias inventore tenetur dolores
                ab nemo?
            </div>
        </div>
    </div>
</div>

{% endblock %}